plugin:liquidglass {
    enabled = 1
    exclude_classes = mpv,helium
    layer_namespaces = quickshell

    window_opacity = 0.90
    layer_opacity = 1.0
    layer_corner_radius = 12
    glass_opacity = 0.78

    blur_strength = 0.32
    blur_iterations = 2

    refraction_strength = 1.15
    chromatic_aberration = 0.90
    lens_distortion = 1.15

    fresnel_strength = 0.46
    specular_strength = 0.38
    edge_thickness = 0.040

    tint_color = 0xb8d8ff00

    brightness = 0.88
    contrast = 1.16
    saturation = 1.14
    vibrancy = 0.32
    adaptive_dim = 0.32
    adaptive_boost = 0.10
}
